logger:
  level: INFO

browser_driver:
  path: driver_Chromium/chromedriver
  download_image_path: images

google:
  image_url: https://www.google.com/search?site=&tbm=isch&source=hp&biw=1873&bih=990&
  # For reason of security, google always change
  # the image_class, so beware that this value
  # may have changed when you are executing the
  # script.
  image_class: YQ4gaf
